# Instructions

* Add your code as indicated in each cell.
* You can add as many cells as you want to experiment with your code and get your code right. Once you are done, remove the cells you have added and keep the original cells.
* Do not alter/delete cells that state **"Do not change or delete this cell".**
* Before you turn this in, make sure everything runs as expected.
> * Start from the very first cell, run all cells one by one, including the cell that computes your total score for this assignment.
> * If you cannot program a specific question and get an error, still run its cell and go to the next cell and keep running it.
* All work must be your own. I use a plagiarism check for coding. Copying and pasting code from friends is not allowed.
* If you attempt to fake passing the tests, you will receive an F, and it will be considered an ethical violation.
* You will need to submit three things:
> 1.   ***The link to your Google Colab notebook file***: Submit the link to your notebook file. To do so, click **Share** on the top right-hand side. Then a box will pop-up. You need to change **"restricted"** to **"anyone with the link."** Then, copy the link and paste it as a comment when submitting the assignment.
> 2.   ***The notebook file***: Download the same file as ipynb. To do so, Go to **File**, select **Download**. Then Click on **ipynb** on the menu box.
> 3.   ***The pdf version of your notebook file***: Download the same file as pdf. To do so, Go to **File**, select **Print**,A menu box will pop up. Then Click on **PDF** on the menu box. This will convert the file into a PDF file, instead of printing it using a printer.

# Background
Assume you developed an app that combines news articles from various resources.
* You need to develop an algorithm that will classify these articles into various categories such as politics, sports, and entertainment based on the content of the news.
* This is called article tagging
* To develop such an algorithm, we will need to process the textual data and then fit algorithms to determine the category of the news article based on the words contained.

# Run Cell Below to Store Your Assignment Score

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

score = {}

# Run Cell Below to Read the Dataset

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

import pandas as pd
import numpy as np

# Read the CSV file using Pandas (pd)
url = 'https://drive.google.com/file/d/1EKWpTfD8jGVYnesfLNpOOEr2wu6p7zeg/view?usp=sharing'
# Extracting the file ID from the URL
file_id = url.split('/')[-2]
# Constructing the download link for the file
download_link = 'https://drive.google.com/uc?export=download&id=' + file_id
# Reading the CSV file from the provided link
df = pd.read_csv(download_link)

# only use the below code if you reach download limit on G-Drive
# df = pd.read_csv('https://raw.githubusercontent.com/marineevy/datasets/main/news.csv')



# If you get a G-Drive Download limit reached warning and cannot do it through GutHub,
# Download the car_prices dataset from canvas
# upload it to you current session and then run the below code
# only use the below code if you cannot load the data using previous two metho

# df = pd.read_csv('/content/news.csv')

print(df.shape)
df.head(2)

(127393, 3)

,date,text,label
0,2018-01-04T15:35:56,Farmers will get subsidies for turning fields ...,politic
1,2018-01-04T15:35:57,Vanuatu bans non-biodegradable plastic to prot...,politic

# Question 1
* Remove the rows in the dataframe `df` where the text variable is null

In [ ]:
###
### YOUR CODE HERE
###
df = df[~df['text'].isnull()]

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

df.shape

(127375, 3)

**Question 1 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
try:
  if (df.shape[0] == 127375):
    score['question 1'] = 'pass'
  else:
    score['question 1'] = 'fail'
except:
  score['question 1'] = 'fail'

score

{'question 1': 'pass'}

# Question 2
* Convert the `text` variable in the dataframe `df` into all lower case

In [ ]:
###
### YOUR CODE HERE
###
df['text'] = df['text'].str.lower()

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

df['text'][0]

'farmers will get subsidies for turning fields back into wildflower meadows after brexit: more than 97% of the uk’s wildflower meadows have been destroyed since the second world war and their loss has played a significant role in the falling numbers of bees, birds and other wildlife.'

**Question 2 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
  if ((df['text'][0][:7] == 'farmers') and (df['text'][1][:7] == 'vanuatu')):
    score['question 2'] = 'pass'
  else:
    score['question 2'] = 'fail'
except:
  score['question 2'] = 'fail'

score

{'question 1': 'pass', 'question 2': 'pass'}

# Question 3
* Remove the stop words. For example "will love" should be
converted to "love".

In [ ]:
###
### YOUR CODE HERE
###
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    if isinstance(text, str):
        return ' '.join([word for word in text.split() if word not in stop_words])
    return text
df['text'] = df['text'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

df['text'][0]

'farmers get subsidies turning fields back wildflower meadows brexit: 97% uk’s wildflower meadows destroyed since second world war loss played significant role falling numbers bees, birds wildlife.'

**Question 3 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
try:
  if (df['text'][0][8:11] == 'get'):
    score['question 3'] = 'pass'
  else:
    score['question 3'] = 'fail'
except:
  score['question 3'] = 'fail'

score

{'question 1': 'pass', 'question 2': 'pass', 'question 3': 'pass'}

# Question 4:
* Remove numbers and special characters such as % or qutation marks from the `text` variable in the dataframe `df`

In [ ]:
###
### YOUR CODE HERE
###
import re
df['text'] = df['text'].map(lambda x: re.sub('[^A-Za-z0-9]', ' ', x))
df['text'] = df['text'].str.replace('\d+', '', regex=True).str.strip()
df['text'] = df['text'].str.replace(' +', ' ', regex=True).str.strip()

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

df['text'][0]

'farmers get subsidies turning fields back wildflower meadows brexit uk s wildflower meadows destroyed since second world war loss played significant role falling numbers bees birds wildlife'

In [ ]:
try:
  if (df['text'][0] == 'farmers get subsidies turning fields back wildflower meadows brexit uk s wildflower meadows destroyed since second world war loss played significant role falling numbers bees birds wildlife'):
    score['question 4'] = 'pass'
  else:
    score['question 4'] = 'fail'
except:
  score['question 4'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass'}

# Question 5
* Create tf-idf for the `text`variable.
* Convert tf-idf to a dataframe named `tfidf_df`
* Add `label` variable in the dataframe `df` to `tfidf_df`

In [ ]:
###
### YOUR CODE HERE
###
from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Step 2: Fit and transform the text data
tfidf_matrix = vectorizer.fit_transform(df['text'])

# Step 3: Convert to DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# Step 4: Add 'label' column from original df
tfidf_df['label'] = df['label'].values

# ✅ Preview the result
print(tfidf_df.shape)
tfidf_df.head()

(127375, 51060)

,aa,aaa,aaaaaetywc,aaas,aadhaar,aadholokam,aae,aagbfmpdgwlvpp,aakaweb,aalto,...,zumbro,zuraibi,zurich,zuzana,zwaan,zwj,zx,zygosity,zynga,zyxel
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

tfidf_df

,aa,aaa,aaaaaetywc,aaas,aadhaar,aadholokam,aae,aagbfmpdgwlvpp,aakaweb,aalto,...,zumbro,zuraibi,zurich,zuzana,zwaan,zwj,zx,zygosity,zynga,zyxel
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127372,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127373,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127374,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**Question 5 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
  if ((tfidf_df.columns[0] == 'aa') & (tfidf_df.columns[-1] == 'zyxel')):
    score['question 5'] = 'pass'
  else:
    score['question 5'] = 'fail'
except:
  score['question 5'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass'}

# Part 2: HR Attrition Background
* HR attrition, also known as employee attrition or employee turnover, refers to the process of employees leaving an organization and the subsequent reduction in the workforce. It can occur due to various reasons, including voluntary resignations, retirements, layoffs, or terminations. Understanding and managing attrition is crucial for organizations because high attrition rates can lead to increased recruitment and training costs, loss of organizational knowledge, decreased employee morale, and reduced productivity.
* So we want to use the historical data to build models that will tell us the probability of an employee leaving the company.

# Run Cell Below to Read the Dataset

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

import pandas as pd

# Using the direct link to the file

# Read the CSV file using Pandas (pd)
url = 'https://drive.google.com/file/d/1-SGPhmw4F7hzBxeJv49lkHwj8yEGgG7S/view?usp=sharing'

# Extracting the file ID from the URL
file_id = url.split('/')[-2]

# Constructing the download link for the file
download_link = 'https://drive.google.com/uc?export=download&id=' + file_id

# Reading the CSV file from the provided link
df = pd.read_csv(download_link)

# only use the below code if you reach download limit on G-Drive
#df = pd.read_csv('https://raw.githubusercontent.com/marineevy/datasets/main/hr_analytics.csv')

# only use the below code if you cannot load the data using previous two methods
#df = pd.read_csv('/content/hr_analytics.csv')

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,...,PerformanceRating,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,3,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,3,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,3,80,1,6,3,3,2,2,2,2

# Question 7
* Identify the names of numerical variables in the dataframe df save it as a list named as `numerical_var`
* Identify the names of categorical variables in the dataframe df and save it as list named as `categorical_var`
* Exclude ythe target variable `Attrition`

In [ ]:
###
### YOUR CODE HERE
###
numerical_var = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
if 'Attrition' in numerical_var:
    numerical_var.remove('Attrition')
categorical_var = df.select_dtypes(include=['object', 'category']).columns.tolist()
if 'Attrition' in categorical_var:
    categorical_var.remove('Attrition')

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
print(numerical_var)
print(categorical_var)

['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount', 'EmployeeID', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']

**Question 6 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
try:
  if ((len(numerical_var) == 23) & (len(categorical_var) == 8)):
    score['question 6'] = 'pass'
  else:
    score['question 6'] = 'fail'
except:
  score['question 6'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass'}

# Question 7
* Are there any variables with majority missing values (more than 50%)? If yes, identify their names and save them in a list named `majority_missing_var`
* Remove these majority missing variables if exist from the dataframe df
* For the remaining variables do the following:
> * Impute the missing values in the numerical variables with the median
> * Impute the missing values in the cotegorical variables with the mode

In [ ]:
###
### YOUR CODE HERE
###
missing_percent = df.isnull().mean()
majority_missing_var = missing_percent[missing_percent > 0.5].index.tolist()
df.drop(columns=majority_missing_var, inplace=True)
numerical_var = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_var = df.select_dtypes(include=['object', 'category']).columns.tolist()
if 'Attrition' in numerical_var:
    numerical_var.remove('Attrition')
if 'Attrition' in categorical_var:
    categorical_var.remove('Attrition')
for col in numerical_var:
    df[col].fillna(df[col].median(), inplace=True)
for col in categorical_var:
    if df[col].isnull().any():
        df[col].fillna(df[col].mode()[0], inplace=True)

<ipython-input-33-a7dd345d6bde>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(majority_missing_var)
df.head(2)

[]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,...,PerformanceRating,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,3,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7

**Question 6 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
  if (len(majority_missing_var) == 0):
    score['question 7'] = 'pass'
  else:
    score['question 7'] = 'fail'
except:
  score['question 7'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass'}

# Question 8
* Create a new variable called DailyRate_Category. This new variable will hold low, medium, and high.
* You will need to discretize the DailyRate variable into three categories with equal lengths.
* For instance, if the DailyRate ranges from 1 to 60, 0-20 will be low, 21-40 will be medium, 41, 60 will be high.
* tip: use pd.cut

In [ ]:
###
### YOUR CODE HERE
###
bins = 3  # Number of equal-width bins
labels = ['low', 'medium', 'high']
df['DailyRate_Category'] = pd.cut(df['DailyRate'], bins=bins, labels=labels)

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
df['DailyRate_Category']

0         high
1          low
2         high
3         high
4       medium
         ...
1465    medium
1466    medium
1467       low
1468    medium
1469    medium
Name: DailyRate_Category, Length: 1470, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']

**Question 8 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
try:
  if (df['DailyRate_Category'].value_counts().low == 484):
    score['question 8'] = 'pass'
  else:
    score['question 8'] = 'fail'
except:
  score['question 8'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass'}

# Question 9
* Encode categorical variables using one-hot encoding
* Make sure to exclude the `Attrition` variable when doing the encoding
* After this process, dataframe `df` should contained the encoded variables and should not contain any categorical variables anymore.

In [ ]:
###
### YOUR CODE HERE
###
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
enc.fit(df[categorical_var])
dummies = pd.DataFrame(enc.transform(df[categorical_var]), columns=enc.get_feature_names_out(categorical_var))

df = pd.concat([df.drop(columns=categorical_var), dummies], axis=1)

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
df.shape

(1470, 54)

**Question 9 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if df.shape[1] == 54:
        score['question 9'] = 'pass'
    else:
        score['question 9'] = 'fail'
except:
      score['question 9'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 10': 'fail',
 'question 9': 'pass'}

# Question 10
* Convert the target variable `Attrition` into a numerical variable
* Yes should mapped to 1 and No should be mapped to 0.

In [ ]:
###
### YOUR CODE HERE
###
# Convert Attrition: 'Yes' → 1, 'No' → 0
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

df['Attrition']

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int64

**Question 10 test case is below**

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if df['Attrition'].sum() == 237:
        score['question 10'] = 'pass'
    else:
        score['question 10'] = 'fail'
except:
      score['question 10'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 10': 'pass',
 'question 9': 'pass'}

# Total Score
* Below Code will give your Total Score. You must run the below code

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

total_score = 0
for i in list(score.values()):
    if i=='pass':
        total_score = total_score + 10
print('your total score is: ', round(total_score))

your total score is:  100

* Below will give the indvidual test case results

In [ ]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 10': 'pass',
 'question 9': 'pass'}